//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatArticulo
    {
        public CatArticulo()
        {
            this.tblArticulo_Bodega = new HashSet<tblArticulo_Bodega>();
            this.tblDetalleVenta = new HashSet<tblDetalleVenta>();
            this.tblDetalleVtaTemp = new HashSet<tblDetalleVtaTemp>();
        }
    
        public int ID_Articulo { get; set; }
        public string Nombre_Articulo { get; set; }
        public string Descripcion { get; set; }
        public int ID_Categoria { get; set; }
        public int ID_Proveedor { get; set; }
        public Nullable<int> ID_Marca { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string RutaImagen { get; set; }
        public string Garantia { get; set; }
    
        public virtual CatCategoria CatCategoria { get; set; }
        public virtual CatMarca CatMarca { get; set; }
        public virtual CatProveedor CatProveedor { get; set; }
        public virtual ICollection<tblArticulo_Bodega> tblArticulo_Bodega { get; set; }
        public virtual ICollection<tblDetalleVenta> tblDetalleVenta { get; set; }
        public virtual ICollection<tblDetalleVtaTemp> tblDetalleVtaTemp { get; set; }
    }
}
