//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatBodega
    {
        public CatBodega()
        {
            this.tblArticulo_Bodega = new HashSet<tblArticulo_Bodega>();
        }
    
        public int ID_Bodega { get; set; }
        public string Nombre_Bodega { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<tblArticulo_Bodega> tblArticulo_Bodega { get; set; }
    }
}
