//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatDepartamento
    {
        public CatDepartamento()
        {
            this.CatMunicipio = new HashSet<CatMunicipio>();
        }
    
        public int ID_Departamento { get; set; }
        public string Nombre_Depto { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<CatMunicipio> CatMunicipio { get; set; }
    }
}
