//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMunicipio
    {
        public CatMunicipio()
        {
            this.CatCliente = new HashSet<CatCliente>();
        }
    
        public int ID_Municipio { get; set; }
        public string Nombre_Municipio { get; set; }
        public Nullable<int> ID_Departamento { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<CatCliente> CatCliente { get; set; }
        public virtual CatDepartamento CatDepartamento { get; set; }
    }
}
