//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatMarca
    {
        public CatMarca()
        {
            this.CatArticulo = new HashSet<CatArticulo>();
        }
    
        public int IDMarca { get; set; }
        public string Nombre_Marca { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<CatArticulo> CatArticulo { get; set; }
    }
}
