//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatUsuario
    {
        public int ID_Usuario { get; set; }
        public string Nombre_User { get; set; }
        public string Apellido1_User { get; set; }
        public string Apellido2_User { get; set; }
        public string UserName { get; set; }
        public string Tipo_Usuario { get; set; }
        public string ImgUser { get; set; }
    }
}
