//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int ID_Informacion { get; set; }
        public string Nombre_Empresa { get; set; }
        public string Propietario { get; set; }
        public string Admonistrador { get; set; }
        public string Ubicacion { get; set; }
        public string Descripcion { get; set; }
        public string Municipio { get; set; }
        public string Departamento { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public Nullable<float> CambioDolar { get; set; }
    }
}
