//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticulo_Bodega
    {
        public int ID_BodegaArticulo { get; set; }
        public int ID_Articulo { get; set; }
        public int ID_Bodega { get; set; }
        public float Precio_Compra { get; set; }
        public float Precion_Venta { get; set; }
        public int Existencia { get; set; }
        public string UserName { get; set; }
    
        public virtual CatArticulo CatArticulo { get; set; }
        public virtual CatBodega CatBodega { get; set; }
    }
}
