//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbono_Cliente
    {
        public int ID_VentaCredito { get; set; }
        public System.DateTime Fecha_Abono { get; set; }
        public float Monto_Abono { get; set; }
        public Nullable<float> Mora { get; set; }
    
        public virtual tblVentaCredito tblVentaCredito { get; set; }
        public virtual tblVentaCredito tblVentaCredito1 { get; set; }
    }
}
