//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetalleVenta
    {
        public int ID_DetalleVenta { get; set; }
        public Nullable<int> ID_Articulo { get; set; }
        public Nullable<int> ID_Venta { get; set; }
        public Nullable<float> SubTotal { get; set; }
        public string Estado { get; set; }
        public Nullable<float> Descuento { get; set; }
        public Nullable<float> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Garantia { get; set; }
    
        public virtual CatArticulo CatArticulo { get; set; }
        public virtual tblVenta tblVenta { get; set; }
    }
}
