//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetalleCpaTemp
    {
        public int ID_ComraTmp { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> ID_Articulo { get; set; }
        public Nullable<decimal> Precio_Compra { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public Nullable<int> ID_Proveedor { get; set; }
        public Nullable<int> ID_Bodega { get; set; }
        public Nullable<int> ID_Marca { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public string UserName { get; set; }
    }
}
