//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPedidos
    {
        public int ID_Compra { get; set; }
        public Nullable<System.DateTime> Fecha_Compra { get; set; }
        public Nullable<System.DateTime> Fecha_Recepcion { get; set; }
        public Nullable<float> Sub_Total { get; set; }
        public Nullable<float> IVA { get; set; }
        public Nullable<float> Descuento { get; set; }
        public Nullable<float> Total { get; set; }
        public string Pendiente_Aprobacion { get; set; }
        public int ID_Proveedor { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual CatProveedor CatProveedor { get; set; }
    }
}
