//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVentaCredito
    {
        public int ID_Venta { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public int ID_Articulo { get; set; }
        public System.DateTime Feche_Venta { get; set; }
        public float Plazos { get; set; }
        public Nullable<float> Prima { get; set; }
        public float Interes { get; set; }
        public Nullable<float> Descuento { get; set; }
    
        public virtual CatCliente CatCliente { get; set; }
        public virtual tblAbono_Cliente tblAbono_Cliente { get; set; }
        public virtual tblAbono_Cliente tblAbono_Cliente1 { get; set; }
    }
}
